name: annrl2023
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - numpy
  - matplotlib
  - ipython
  - pylint
  - black
  - mypy
  - notebook
  - jupyter
  - scikit-learn
  - tqdm
  - pytorch
  - pytorch
  - torchvision
  - networkx
  - pyyaml
  - pandas
  - gym
